import structlog

from app.agents.claude_client import ClaudeClient
from app.models.event import Event
from app.utils.diff_generator import apply_section_replacement, generate_diff

logger = structlog.get_logger()

EDIT_SYSTEM_PROMPT = """You are a technical writer performing surgical documentation edits.
Your rule: change the minimum number of words necessary to make the documentation accurate.
Preserve the existing tone, style, and formatting exactly. Do not add marketing language.
Do not rewrite sections that are not stale. Return only the replacement text, nothing else."""


class UpdateGenerator:
    def __init__(self, claude: ClaudeClient) -> None:
        self._claude = claude

    async def generate_update(
        self,
        event: Event,
        doc: dict,
        analysis: dict,
    ) -> dict:
        original_section = analysis["original_section"]
        suggested_content = analysis.get("suggested_content", original_section)

        proposed_content = await self._refine_edit(
            event=event,
            original_section=original_section,
            suggested_content=suggested_content,
            evidence=analysis.get("evidence", {}),
        )

        full_new_file = apply_section_replacement(
            full_doc=doc["content"],
            original_section=original_section,
            proposed_section=proposed_content,
        )

        diff_markdown = generate_diff(
            original=original_section,
            proposed=proposed_content,
            filename=doc["path"],
        )

        pr_title = self._build_pr_title(event, doc["path"])
        pr_body = self._build_pr_body(event, analysis, diff_markdown, doc.get("html_url", ""))

        return {
            "original_content": original_section,
            "proposed_content": proposed_content,
            "full_new_file": full_new_file,
            "diff_markdown": diff_markdown,
            "pr_title": pr_title,
            "pr_body": pr_body,
        }

    async def _refine_edit(
        self,
        event: Event,
        original_section: str,
        suggested_content: str,
        evidence: dict,
    ) -> str:
        pr_payload = event.raw_payload.get("pull_request", {})
        pr_title = pr_payload.get("title", "")
        reasoning = evidence.get("reasoning", "")

        prompt = f"""Refine this documentation edit to be minimal and accurate.

PR that triggered this: {pr_title}
Reason for change: {reasoning}

Original text:
{original_section}

Proposed replacement:
{suggested_content}

Return only the final replacement text. No explanation, no code fences, no extra commentary.
Make it as close to the original style as possible while fixing the factual error."""

        try:
            result = await self._claude.generate(
                user_prompt=prompt,
                system_prompt=EDIT_SYSTEM_PROMPT,
                cache_system_prompt=True,
            )
            return result.strip()
        except Exception as e:
            logger.warning("refine_edit_failed", error=str(e))
            return suggested_content

    def _build_pr_title(self, event: Event, doc_path: str) -> str:
        pr_payload = event.raw_payload.get("pull_request", {})
        pr_title = pr_payload.get("title", "")
        return f"Update {doc_path} — triggered by: {pr_title}"[:100]

    def _build_pr_body(
        self,
        event: Event,
        analysis: dict,
        diff_markdown: str,
        doc_html_url: str,
    ) -> str:
        pr_payload = event.raw_payload.get("pull_request", {})
        pr_number = pr_payload.get("number", "")
        pr_title = pr_payload.get("title", "")
        pr_url = pr_payload.get("html_url", "")
        confidence = analysis.get("confidence", 0.0)
        evidence = analysis.get("evidence", {})
        event_signals = evidence.get("event_signals", [])
        doc_issues = evidence.get("doc_issues", [])
        reasoning = evidence.get("reasoning", "")

        signals_md = "\n".join(f"  - {s}" for s in event_signals) or "  - (none)"
        issues_md = "\n".join(f"  - {i}" for i in doc_issues) or "  - (none)"

        original_pr_link = f"[#{pr_number} — {pr_title}]({pr_url})" if pr_url else f"#{pr_number}"
        doc_link = f"[View doc]({doc_html_url})" if doc_html_url else ""

        return f"""## AI Documentation Update

**Confidence:** {confidence:.0%}
**Triggered by:** {original_pr_link}
{doc_link}

### Why this update is needed

**Event signals:**
{signals_md}

**Doc issues:**
{issues_md}

**Reasoning:** {reasoning}

### Proposed change

{diff_markdown}

---
*Generated by AI Documentation Agent. Review carefully before merging.*"""
